apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: awscredentials.kai.aws-operator
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: kai.aws-operator
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                awsAccessKey:
                  type: string
                awsSecretAccessKey:
                  type: string
                workload:
                  type: string
                loginSucceded:
                  type: boolean
                active:
                  type: boolean
      selectableFields:
      - jsonPath: .spec.loginSucceded
      - jsonPath: .spec.active
      - jsonPath: .spect.worklload
      additionalPrinterColumns:
      - jsonPath: .spec.loginSucceded
        name: Login
        type: string
      - jsonPath: .spec.active
        name: Active
        type: string
      - jsonPath: .spec.workload
        name: Workload
        type: string
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: awscredentials
    # singular name to be used as an alias on the CLI and for display
    singular: awscredential
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: AwsCredential
    # shortNames allow shorter string to match your resource on the CLI
    #shortNames:
    #- ""