apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-cli-operator
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-cli-operator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete", "update", "patch"]
- apiGroups: ["kai.aws-operator"]
  resources: ["awscredentials"]
  verbs: ["get", "list", "create", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-cli-operator
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-cli-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-cli-operator
subjects:
- kind: ServiceAccount
  name: aws-cli-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-cli-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-cli-operator
subjects:
- kind: ServiceAccount
  name: aws-cli-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
spec:
  selector:
    matchLabels:
      app: aws-cli-operator
      component: manager
  replicas: 1
  template:
    metadata:
      labels:
        app: aws-cli-operator
        component: manager
    spec:
      serviceAccountName: aws-cli-operator
      containers:
      - name: operator
        image: aws-cli-operator:v1
        env:
        - name: K8S_NAMESPACE
          value: "default"
        resources:
          limits: 
            cpu: 100m
            memory: 100Mi
